export enum SpamType {
    CONTENT_SPAM = "CONTENT_SPAM",
    CROSS_CONTENT_SPAM = "CROSS_CONTENT_SPAM",
    USER_SPAM = "USER_SPAM",
    NEW_USER_SPAM = "NEW_USER_SPAM",
    FAST_JOINERS_SPAM = "FAST_JOINERS_SPAM"
}
